python -W ignore test.py \
--pretrained_model_path preset/models/stable-diffusion-2-base \
--prompt None \
--seesr_model_path preset/train_output/LSDIR/test_2/checkpoint-7500 \
--ram_ft_path preset/models/DAPE.pth \
--image_path preset/datasets/test_datasets/DRealSR/test_LR_10_img \
--output_dir preset/datasets/output/DRealSR \
--recompute_metrics \
--datasets DRealSR \
--start_point lr \
--num_inference_steps 50 \
--guidance_scale 5.5 \
--process_size 512